version: '3.2'
services:
   proxy:
      image: highmed/bpe_proxy
      restart: on-failure
      ports:
      - 8080:80
      - 8443:443
      volumes:
      -  type: bind
         source: ./proxy/ssl
         target: /usr/local/apache2/ssl
      environment:
         HTTPS_SERVER_NAME_PORT: localhost:8443
         APP_SERVER_IP: 172.28.3.3
      networks:
         frontend:
            ipv4_address: 172.28.3.2
      depends_on:
      - app
   app:
      image: highmed/bpe
      restart: on-failure
# Ports for jmx debug connections
#      ports:
#      - 9020:9020
#      - 9021:9021
      volumes:
      -  type: bind
         source: ./app/conf
         target: /opt/bpe/conf
         read_only: true
      -  type: bind
         source: ./app/plugin
         target: /opt/bpe/plugin
         read_only: true
      -  type: bind
         source: ./app/process
         target: /opt/bpe/process
         read_only: true
      -  type: bind
         source: ./app/log
         target: /opt/bpe/log
      -  type: bind
         source: ./app/last_event
         target: /opt/bpe/last_event
      environment:
         TZ: Europe/Berlin
# Use EXTRA_JVM_ARGS to specify special jvm parameters, e.g. jmx connection config below
#         EXTRA_JVM_ARGS: -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=9020 -Dcom.sun.management.jmxremote.rmi.port=9021 -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.local.only=false
      networks:
         frontend:
            ipv4_address: 172.28.3.3
         backend:
            ipv4_address: 172.28.3.130
         fhir_bpe:
            ipv4_address: 172.28.2.3
      depends_on:
      - db
   db:
      image: postgres:13
      restart: on-failure
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U liquibase_user -d bpe"]
         interval: 10s
         timeout: 5s
         retries: 5
      environment:
         POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
         POSTGRES_USER: liquibase_user
         POSTGRES_DB: bpe
      networks:
         backend:
            ipv4_address: 172.28.3.131
      secrets:
      - postgres_password
secrets:
   postgres_password:
      file: ./db/conf/postgres_password
networks:
   frontend:
      driver: bridge
      ipam:
         driver: default
         config:
         - subnet: 172.28.3.0/25
   backend:
      driver: bridge
      ipam:
         driver: default
         config:
         - subnet: 172.28.3.128/25
   fhir_bpe:
      external: true