version: '3.2'
services:
   proxy:
      image: highmed/fhir_proxy
      restart: on-failure
      ports:
      - 80:80
      - 443:443
      volumes:
      -  type: bind
         source: ./proxy/ssl
         target: /usr/local/apache2/ssl
      environment:
         HTTPS_SERVER_NAME_PORT: localhost:443
         APP_SERVER_IP: 172.28.1.3
      networks:
         frontend:
            ipv4_address: 172.28.1.2
         bpe:
            ipv4_address: 172.28.2.2
            aliases:
            - fhir
      depends_on:
      - app
   app:
      image: highmed/fhir
      restart: on-failure
 # Ports for jmx debug connections
 #     ports:
 #     - 9010:9010
 #     - 9011:9011
      volumes:
      -  type: bind
         source: ./app/conf
         target: /opt/fhir/conf
      -  type: bind
         source: ./app/log
         target: /opt/fhir/log
      environment:
         TZ: Europe/Berlin
# Use EXTRA_JVM_ARGS to specify special jvm parameters, e.g. jmx connection config below
#         EXTRA_JVM_ARGS: -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9011 -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.local.only=false
      networks:
         frontend:
            ipv4_address: 172.28.1.3
         backend:
            ipv4_address: 172.28.1.130
      depends_on:
      - db
   db:
      image: postgres:13
      restart: on-failure
#     Port for database connections
#      ports:
#           - 5432:5432
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U liquibase_user -d fhir"]
         interval: 10s
         timeout: 5s
         retries: 5
      environment:
         POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
         POSTGRES_USER: liquibase_user
         POSTGRES_DB: fhir
      networks:
         backend:
            ipv4_address: 172.28.1.131
      secrets:
      - postgres_password
secrets:
   postgres_password:
      file: ./db/conf/postgres_password
networks:
   frontend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.28.1.0/25
   backend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.28.1.128/25
   bpe:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.28.2.0/24