version: '3.2'
services:
   proxy:
      image: registry:5000/highmed/bpe_proxy
      restart: on-failure
      ports:
      - 8080:80
      - 8443:443
      volumes:
      -  type: bind
         source: ./proxy/ssl
         target: /usr/local/apache2/ssl
         read_only: true
      environment:
         TZ: Europe/Berlin
         HTTPS_SERVER_NAME_PORT: medic1:8443
         APP_SERVER_IP: 172.28.3.3
      networks:
         frontend:
            ipv4_address: 172.28.3.2
      depends_on:
      - app
   app:
      image: registry:5000/highmed/bpe
      restart: on-failure
      volumes:
      -  type: bind
         source: ./app/conf
         target: /opt/bpe/conf
         read_only: true
      -  type: bind
         source: ./app/plugin
         target: /opt/bpe/plugin
         read_only: true
      -  type: bind
         source: ./app/process
         target: /opt/bpe/process
         read_only: true
      -  type: bind
         source: ./app/log
         target: /opt/bpe/log
      -  type: bind
         source: ./app/last_event
         target: /opt/bpe/last_event
      environment:
         TZ: Europe/Berlin
      networks:
         frontend:
            ipv4_address: 172.28.3.3
         backend:
            ipv4_address: 172.28.3.130
         fhir_bpe:
            ipv4_address: 172.28.2.3
      extra_hosts:
      - "ttp:10.42.0.10"
      - "medic1:10.42.0.11"
      - "medic2:10.42.0.12"
      - "medic3:10.42.0.13"
      depends_on:
      - db
   db:
      image: postgres:13
      restart: on-failure
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U liquibase_user -d bpe"]
         interval: 10s
         timeout: 5s
         retries: 5
      environment:
         TZ: Europe/Berlin
         POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
         POSTGRES_USER: liquibase_user
         POSTGRES_DB: bpe
      networks:
         backend:
            ipv4_address: 172.28.3.131
      secrets:
      - postgres_password
secrets:
   postgres_password:
      file: ./db/conf/postgres_password
networks:
   frontend:
      driver: bridge
      ipam:
         driver: default
         config:
         - subnet: 172.28.3.0/25
   backend:
      driver: bridge
      ipam:
         driver: default
         config:
         - subnet: 172.28.3.128/25
   fhir_bpe:
      external: true